### PR TITLE
GMCM Support

### LINKED ISSUE #2: [Suggestion] GMCM Support
~~- Add a setting to hide universal loved item to display less item~~

Ok nevermind there is already this options, i just never opened config.json so.... edit suggestion, add GMCM support

### PR DESCRIPTION
**Pull request by Tenebrosful**
- Add GMCM Support
- i18n Support for options

### CODE REVIEW

**Comment by Tenebrosful** [comment]
(❑ = untranslated, ↻ = partly translated, ✓ = fully translated)

&nbsp;     | Gift Taste Helper Continued x2
:--------- | :--------------------------------
Chinese    | [↻](GiftTasteHelper/i18n/zh.json)
French     | [✓](GiftTasteHelper/i18n/fr.json)
German     | [↻](GiftTasteHelper/i18n/de.json)
Hungarian  | [❑](GiftTasteHelper/i18n)
Italian    | [❑](GiftTasteHelper/i18n)
Japanese   | [↻](GiftTasteHelper/i18n/ja.json)
Korean     | [↻](GiftTasteHelper/i18n/ko.json)
Portuguese | [↻](GiftTasteHelper/i18n/pt.json)
Russian    | [↻](GiftTasteHelper/i18n/ru.json)
Spanish    | [↻](GiftTasteHelper/i18n/es.json)
[Thai]     | [↻](GiftTasteHelper/i18n/th.json)
Turkish    | [↻](GiftTasteHelper/i18n/tr.json)

[Thai]: https://www.nexusmods.com/stardewvalley/mods/7052

**Comment by Tenebrosful** [comment]
- Added translation on other language with ChatGPT, need verification for translation + text fit
(❑ = untranslated, ↻ = partly translated, ✓ = fully translated)

&nbsp;     | Gift Taste Helper Continued x2
:--------- | :--------------------------------
Chinese    | [✓](GiftTasteHelper/i18n/zh.json) (ChatGPT, need verification)
French     | [✓](GiftTasteHelper/i18n/fr.json) (Me, native)
German     | [✓](GiftTasteHelper/i18n/de.json) (ChatGPT, need verification)
Hungarian  | ❑
Italian    | ❑
Japanese   | [✓](GiftTasteHelper/i18n/ja.json) (ChatGPT, need verification)
Korean     | [✓](GiftTasteHelper/i18n/ko.json) (ChatGPT, need verification)
Portuguese | [✓](GiftTasteHelper/i18n/pt.json) (ChatGPT, need verification)
Russian    | [✓](GiftTasteHelper/i18n/ru.json) (ChatGPT, need verification)
Spanish    | [✓](GiftTasteHelper/i18n/es.json) (ChatGPT, need verification)
[Thai]     | [✓](GiftTasteHelper/i18n/th.json) (ChatGPT, need verification)
Turkish    | [✓](GiftTasteHelper/i18n/tr.json) (ChatGPT, need verification)

[Thai]: https://www.nexusmods.com/stardewvalley/mods/7052

**Comment by Tenebrosful** [comment]
#2

**Review by JoXW100 — APPROVED** [review]
Great changes, one issue with this change is that the settings are only applied after reloading a savegame since the mod stores registered gifts in memory. I will fix this after merging the changes.

**Pull request merged**
